// packages/ellamaka-release/src/build-identity.ts
//
// Build-time helper that produces the embedded ReleaseIdentity JSON for the
// CLI binary. In a real release workflow, a release-context.json file
// (generated by src/cli/context.ts) provides the full release identity. For
// local/dev builds, a development identity is produced.
//
// This module runs under Bun at build time only; it must not import any
// runtime modules that depend on the bundled binary.

export type BuildIdentityInput = {
  isRelease: boolean
  version: string
  channel: string
  // In a real release workflow, the release-context.json path is passed via
  // an env var. When present, it is the source of truth for the release
  // identity (upstream, gitCommit, builtAt, workflowRunId).
  releaseContextPath?: string
}

type Identity = Record<string, unknown>

/**
 * Build the embedded ReleaseIdentity for a CLI build. Returns a development
 * identity when isRelease is false or no release context is available.
 */
export function buildReleaseIdentityForBuild(input: BuildIdentityInput): Identity {
  // Release context path is provided by the publish workflow via env var.
  const ctxPath = input.releaseContextPath ?? process.env.ELLAMAKA_RELEASE_CONTEXT_PATH
  if (input.isRelease && ctxPath) {
    const ctx = JSON.parse(readFileSync(ctxPath, "utf8"))
    return {
      schemaVersion: 2,
      kind: "release",
      product: "ellamaka-cli",
      version: ctx.version,
      channel: ctx.channel,
      upstream: ctx.upstream,
      build: ctx.build,
    }
  }

  // Development identity. Per docs/DISTRIBUTION.md §5.4, dev identities
  // must not carry build.sourceTag or build.workflowRunId. gitCommit and
  // builtAt are optional and only present if available.
  // The channel is reported verbatim for the known dev channels (main,
  // local); anything else folds to local defensively. Desktop beta local
  // packaging maps its identity channel on the Desktop side.
  const devChannel = ["main", "local"].includes(input.channel) ? input.channel : "local"
  const identity: Identity = {
    schemaVersion: 2,
    kind: "development",
    product: "ellamaka-cli",
    version: input.version,
    channel: devChannel,
  }
  const build: Record<string, unknown> = {}
  const commit = process.env.ELLAMAKA_BUILD_COMMIT
  if (commit && /^[0-9a-f]{40}$/.test(commit)) build.gitCommit = commit
  const builtAt = new Date().toISOString().replace(/\.\d{3}Z$/, "Z")
  build.builtAt = builtAt
  if (Object.keys(build).length > 0) identity.build = build
  return identity
}

// Inline readFileSync to avoid a top import that breaks when this module is
// loaded in a non-Bun context (e.g. ts-node for typecheck).
import { readFileSync } from "node:fs"
